'use client';

import Image from 'next/image';
import Link from 'next/link';
import { FormEvent, useMemo, useState } from 'react';
import { config, formatPrice, getProductImage } from '@/lib/data';
import { useStore } from '@/components/store-provider';
import { Icon } from '@/components/icons';

export default function CheckoutPage() {
  const { cartItems, clearCart } = useStore();
  const [delivery, setDelivery] = useState('dhaka');
  const [payment, setPayment] = useState('cod');
  const [submitting, setSubmitting] = useState(false);
  const subtotal = useMemo(() => cartItems.reduce((sum, { item, product }) => sum + product.price * item.quantity, 0), [cartItems]);
  const deliveryCharge = delivery === 'dhaka' ? config.deliveryChargeInsideDhaka : config.deliveryChargeOutsideDhaka;
  const total = subtotal + (cartItems.length ? deliveryCharge : 0);
  const submitOrder = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSubmitting(true); window.setTimeout(() => { clearCart(); window.location.href = '/order-confirmed'; }, 500); };

  if (!cartItems.length) return <section className="checkout-page"><div className="container"><div className="empty-state"><div className="empty-icon"><Icon name="shopping-bag" size={27} /></div><h2>অর্ডার করার মতো কোনো পণ্য নেই</h2><p>আগে কার্টে পণ্য যোগ করুন, তারপর অর্ডার সম্পন্ন করুন।</p><Link href="/shop" className="btn btn-dark">পণ্য দেখুন <Icon name="arrow-right" size={16} /></Link></div></div></section>;

  return <section className="checkout-page"><div className="container"><div className="breadcrumbs"><Link href="/">হোম</Link><span>/</span><Link href="/cart">কার্ট</Link><span>/</span><span>অর্ডার সম্পন্ন করুন</span></div><div className="checkout-heading"><div><h1>অর্ডার সম্পন্ন করুন</h1><p>আপনার তথ্য দিন—বাকি কাজটি আমরা সহজ করে দিচ্ছি।</p></div><span className="demo-checkout-label"><Icon name="lock" size={14} /> নিরাপদ Demo checkout</span></div><form className="checkout-layout" onSubmit={submitOrder}><div><div className="form-card"><h2><span>১</span>ক্রেতার তথ্য</h2><div className="form-grid"><div className="form-field"><label htmlFor="name">নাম *</label><input id="name" required placeholder="আপনার পূর্ণ নাম" /></div><div className="form-field"><label htmlFor="phone">মোবাইল নম্বর *</label><input id="phone" required type="tel" placeholder="০১XXXXXXXXX" /></div><div className="form-field full"><label htmlFor="address">সম্পূর্ণ ঠিকানা *</label><textarea id="address" required placeholder="বাড়ি, রোড, এলাকার নাম"></textarea></div><div className="form-field"><label htmlFor="area">এলাকা *</label><input id="area" required placeholder="যেমন: মিরপুর ১০" /></div><div className="form-field"><label htmlFor="district">জেলা *</label><select id="district" defaultValue="ঢাকা"><option>ঢাকা</option><option>চট্টগ্রাম</option><option>সিলেট</option><option>রাজশাহী</option><option>খুলনা</option><option>অন্যান্য</option></select></div></div></div>
      <div className="form-card"><h2><span>২</span>ডেলিভারি</h2><div className="delivery-options"><label className="radio-card"><input type="radio" name="delivery" value="dhaka" checked={delivery === 'dhaka'} onChange={() => setDelivery('dhaka')} /><span><strong>ঢাকার মধ্যে</strong><br />১–৩ দিন · {formatPrice(config.deliveryChargeInsideDhaka)}</span></label><label className="radio-card"><input type="radio" name="delivery" value="outside" checked={delivery === 'outside'} onChange={() => setDelivery('outside')} /><span><strong>ঢাকার বাইরে</strong><br />২–৫ দিন · {formatPrice(config.deliveryChargeOutsideDhaka)}</span></label></div></div>
      <div className="form-card"><h2><span>৩</span>পেমেন্ট</h2><div className="payment-options"><label className="radio-card payment-card"><div><input type="radio" name="payment" value="cod" checked={payment === 'cod'} onChange={() => setPayment('cod')} /><strong>ক্যাশ অন ডেলিভারি</strong></div><small>নির্বাচিত পণ্যে প্রযোজ্য</small></label><label className="radio-card payment-card"><div><input type="radio" name="payment" value="bkash" checked={payment === 'bkash'} onChange={() => setPayment('bkash')} /><strong>bKash / Nagad</strong></div><small>Demo payment UI</small></label><label className="radio-card payment-card"><div><input type="radio" name="payment" value="card" checked={payment === 'card'} onChange={() => setPayment('card')} /><strong>Card</strong></div><small>Demo payment UI</small></label><label className="radio-card payment-card"><div><input type="radio" name="payment" value="emi" checked={payment === 'emi'} onChange={() => setPayment('emi')} /><strong>EMI</strong></div><small>যোগ্যতার শর্ত প্রযোজ্য</small></label></div><div className="demo-note">এটি একটি Demo Website। কোনো real payment gateway বা order backend সংযুক্ত নেই।</div></div></div><aside className="checkout-summary"><div className="cart-summary"><h2>অর্ডারের সারাংশ</h2>{cartItems.map(({ item, product }) => <div className="checkout-product" key={`${item.productId}-${item.variant}`}><div className="checkout-product-image"><Image src={getProductImage(product)} alt={product.name} fill sizes="50px" /></div><div><strong>{product.name}</strong><small>{item.quantity} × {formatPrice(product.price)}</small></div><span>{formatPrice(product.price * item.quantity)}</span></div>)}<div className="summary-line"><span>পণ্যের মোট</span><strong>{formatPrice(subtotal)}</strong></div><div className="summary-line"><span>ডেলিভারি চার্জ</span><strong>{formatPrice(deliveryCharge)}</strong></div><div className="summary-line summary-total"><span>সর্বমোট</span><strong>{formatPrice(total)}</strong></div><button className="btn btn-blue" type="submit" style={{ width: '100%', marginTop: 15 }} disabled={submitting}>{submitting ? 'অর্ডার তৈরি হচ্ছে...' : 'অর্ডার নিশ্চিত করুন'} <Icon name="arrow-right" size={16} /></button></div></aside></form></div></section>;
}
